platform :ios, '9.0'

target 'VOLA' do
    use_frameworks!

    # code verification
    pod 'SwiftLint'

    # Asyncronous calls without pyramide effect
    pod 'PromiseKit', '~> 4.1.3'

    # Rest API management
    pod 'AlamofireObjectMapper', '~> 4.0.2'

    # Cache images
    pod 'Kingfisher', '~> 3.4.0'

    # UI Util
    pod 'NVActivityIndicatorView', '~> 3.4'
    pod 'TPKeyboardAvoiding', '~> 1.3.1'
    pod 'GoogleMaps'
    pod 'PopupDialog', '~> 0.5'
    pod 'FRHyperLabel', '~> 1.0.4'

    pod 'ReachabilitySwift', '~> 3'

    pod 'FacebookCore', '~> 0.2'
    pod 'FacebookLogin', '~> 0.2'
    pod 'FacebookShare', '~> 0.2'
    pod 'FBSDKCoreKit', '~> 4.22.1'
    pod 'FBSDKLoginKit', '~> 4.22.1'
    pod 'FBSDKShareKit', '~> 4.22.1'
    pod 'Google/SignIn', '~> 3.0.3'

    # Mock Testing
    pod 'Cuckoo', '~> 0.9.2'
end
