platform :ios, '9.0'

target 'VOLA' do
    use_frameworks!

    # code verification
    pod 'SwiftLint'

    # Asyncronous calls without pyramide effect
    pod 'PromiseKit', '~> 4.1.3'

    # Rest API management
    pod 'AlamofireObjectMapper', '~> 4.0.2'

    # Cache images
    pod 'Kingfisher', '~> 3.4.0'

    # UI Util
    pod 'NVActivityIndicatorView', '~> 3.4'
    pod 'TPKeyboardAvoiding', '~> 1.3.1'
    pod 'GoogleMaps'
    pod 'PopupDialog', '~> 0.5'
    pod 'FRHyperLabel'

    pod 'ReachabilitySwift', '~> 3'

    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'Google/SignIn'
end
